"""
PDF Report Generator

Author: Your Name
Project: Windows Security Log Analyzer
"""

from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


def generate_pdf(stats, events):
    """
    Generate a professional investigation PDF report.

    Parameters
    ----------
    stats : dict
        Dashboard statistics.

    events : list
        Filtered security events.

    Returns
    -------
    Path
        Generated PDF file path.
    """

    output_folder = Path("reports/generated")

    output_folder.mkdir(
        parents=True,
        exist_ok=True
    )

    filename = output_folder / "investigation_report.pdf"

    doc = SimpleDocTemplate(str(filename))

    styles = getSampleStyleSheet()

    story = []

    # ---------------------------------------------------
    # Title
    # ---------------------------------------------------

    story.append(
        Paragraph(
            "Windows Security Log Analyzer",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 15))

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    # ---------------------------------------------------
    # Investigation Summary
    # ---------------------------------------------------

    story.append(
        Paragraph(
            "Investigation Summary",
            styles["Heading2"]
        )
    )

    story.append(Spacer(1, 10))

    summary = [

        ["Metric", "Value"],

        ["Total Events", stats["total_events"]],

        ["Successful Logins", stats["successful_logins"]],

        ["Failed Logins", stats["failed_logins"]],

        ["Privilege Escalations", stats["privilege_escalations"]],

        ["Account Creations", stats["account_creations"]],

        ["Password Changes", stats["password_changes"]],

        ["Account Lockouts", stats["account_lockouts"]],

        ["Account Deletions", stats["account_deletions"]]

    ]

    summary_table = Table(summary)

    summary_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

            ("ALIGN", (0, 0), (-1, -1), "CENTER")

        ])

    )

    story.append(summary_table)

    story.append(Spacer(1, 25))

    # ---------------------------------------------------
    # Recent Events
    # ---------------------------------------------------

    story.append(

        Paragraph(

            "Recent Security Events",

            styles["Heading2"]

        )

    )

    story.append(Spacer(1, 10))

    table_data = [

        [

            "Timestamp",

            "Event ID",

            "Username",

            "Computer"

        ]

    ]

    for event in events[:10]:

        table_data.append([

            str(event["timestamp"]),

            str(event["event_id"]),

            str(event["username"]),

            str(event["computer"])

        ])

    events_table = Table(table_data)

    events_table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.grey),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 8),

            ("FONTSIZE", (0, 0), (-1, -1), 8),

            ("ALIGN", (0, 0), (-1, -1), "CENTER")

        ])

    )

    story.append(events_table)

    story.append(Spacer(1, 25))

    # ---------------------------------------------------
    # Footer
    # ---------------------------------------------------

    story.append(

        Paragraph(

            "<b>Generated by Windows Security Log Analyzer</b>",

            styles["Italic"]

        )

    )

    doc.build(story)

    return filename